### ISSUE TITLE
run middleware before and after

### ISSUE THREAD

**Issue by agonbina** [vdemedes/ronin#14]
would be great if we can choose to run the middleware functions either before or after ```.run```
Instead of ```use```:
```js
{
  before: [  'midd1'  ],
  after: [ 'midd2' ]
}
```

**Comment by vdemedes** [comment]
Thanks for suggestion, will implement in future releases.

**Comment by agonbina** [comment]
Another recommendation would be to add an api to easily save data from the hooks in the global scope:
read-package.js hook
```js
function(next) {
 // Open package.json if it exists and store its contents
  var pkg = ...
  this.state({
    version: pkg.version,
    dependencies: pkg.dependencies
  })
  next()
}
```

In my commands I can use the ```read-package``` middleware and retrieve the state:
```js
use: [ 'read-package'],
run: function() {
  var pkg = this.hook('read-package').state()
  // pkg.version === '1.0.0'
  // pkg.dependencies === { ... }
}
```

This way you can very easily add common middleware that is used in different commands and have a clear convention of how the global state is accessed, instead of adding random properties to ```this.global```

**Comment by vdemedes** [comment]
@agonbina I think this does not fit with the middleware/hooks concept. I imagine it as a chain of functions, that can affect the path to the main command or alter its behavior. For this use case I would rather make a separate script in lib/read-package.js and use it as a helper function.

**Comment by agonbina** [comment]
I think in frameworks like express you can attach data to the middleware chain,  like the req object thats passed in as an arg to each middleware function. But yeah for that use case I could do as you said, but still I don't see a clean  way to share state between "hooks" as they are running, besides ```this.global[prop] = ...```?

**Comment by vdemedes** [comment]
@agonbina Currently no, `this.global` is the only way to share data that Ronin provides.

**Comment by agonbina** [comment]
:+1: I'll just use ```this.global[middleware-id]``` when I need it
