### ISSUE TITLE
Multiple commands folder

### ISSUE THREAD

**Issue by jboulhous** [vdemedes/ronin#16]
Hello,
Thank you for this cool project.
I would like to create an app and let the user have a local commands folder to process.cwd().
if i could do 
```
var program = ronin();
var globalUserTasks = '/path/to/some/global/user/tasks'
program.set({
    path: [__dirname, globalUserTasks,process.cwd()]
});

program.run();
```
or
```
program.set({
   commands: [additional user commands]
})
```
May be i need to extend Program and rewrite setupCommands, _get, get, set.
What de you think!
would you please point some cool way so i can get what i want.

**Comment by vdemedes** [comment]
Hello Jamal, that is not possible at the moment and I don't think it should be in Ronin, because this is way too uncommon case to support by default.
