### ISSUE TITLE
Object.assign polyfill doesn't return anything.

### ISSUE THREAD

**Issue by sorohan** [vdemedes/ronin#19]
The Object.assign polyfill should return a value, as described here:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by vdemedes** [comment]
Hello Ben, thanks for using Ronin! Thanks for pointing this out, I should not have used a polyfill at all. I will remove this code in favor of `object-assign` package.

**Comment by sorohan** [comment]
Great. That's what I did on my project to workaround this.

**Comment by vdemedes** [comment]
Updated version is available on npm as `ronin@0.3.11`, thank you!
