### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by pyros2097** [vdemedes/ronin#24]
I'm getting this error when I do `ronin new hello-world` 
 `error	spawn ENOENT`.
Here's my environment
```
Node: 0.10.40
NPM: 1.4.28
OS: Ubuntu 14.04
```

**Comment by vdemedes** [comment]
New version of Ronin is coming soon and I will switch to Yeoman to prevent these kinds of issues. As for now, I recommend you to browse [Ronin's website](http://vdemedes.github.io/ronin) for information on how to use it.
