### ISSUE TITLE
Add optional desc property for options

### ISSUE THREAD

**Issue by fnky** [vdemedes/ronin#26]
It would be nice to be able to add descriptions to options using an optional `desc` property.

```js
options: {
  port: {
    type: 'number',
    default: 8080,
    desc: 'use port for something'
  },
  force: {
    type: 'boolean',
    alias: 'f',
    desc: 'force some behavior'
  }
}
```

Would generate this help message on `app command -h`

```
Usage: app command [OPTIONS]

  Doing some command

Options:
  --port <port>  use port for something (default: 8080)
  -f, --force    force some behavior  
```

**Comment by vdemedes** [comment]
I am working on the next version of Ronin in the *next* branch. This feature is already implemented there, so try installing that branch, instead of version on the npm.
