### ISSUE TITLE
run method on Program does not pass global/Program options

### ISSUE THREAD

**Issue by fnky** [vdemedes/ronin#27]
When setting global options making a new `Program` and overwriting `run()` method, neither options are passed to arguments nor is `this.global` available.

```js
var program = ronin({
  path: path.join(__dirname),
  desc: 'My program',

  options: {
    cat: {
      type: 'string'
    }
  },

  run: function (cat) {
    console.log(cat) // => undefined
    console.log(this.global) // => undefined
  }
})
```

**Comment by vdemedes** [comment]
You should not overwrite `run()` method of a program. You should only overwrite `run()` method of a **command**.

**Comment by fnky** [comment]
@vdemedes Then how would I be able to make a program without commands (without hacking around and/or use another library for parsing args) e.g.

```sh
myProgram someValue anotherValue --option value --flag
```

**Comment by vdemedes** [comment]
Currently there's no way and I don't plan on doing it at the moment. Ronin is suitable for programs with commands. If you need a program, that does only one task, then you better not use Ronin and go for [minimist](https://npmjs.org/package/minimist) + [minimist-options](https://npmjs.org/package/minimist-options).
