### ISSUE TITLE
Ronin rated as insecure by bithound because of minimatch dependency

### ISSUE THREAD

**Issue by megastef** [vdemedes/ronin#38]
See https://snyk.io/vuln/npm:minimatch:20160620 please update dependencies.

**Comment by vadimdemedes** [comment]
Sorry, but this module is temporarily unsupported. Consider using [meow](https://npm.im/meow) or [args](https://npm.im/args).

**Comment by vadimdemedes** [comment]
Added a note to the top of readme to prevent confusion for future visitors.
